### ISSUE TITLE
Issues List

### ISSUE THREAD

**Issue by tapan288** [5balloons/laravel-smart-ads#1]
### Description
- When I initially loaded the page, the design was not loading properly, the instructions to run `npm install` and `npm run dev` after publishing the assets are missing in the docs
- The automatic ad placement feature seems a bit confusing, I tried it but don't see the ad/markup rendered anywhere,  maybe there's an issue with it? A proper description of what it is and how it works would be helpful to the package users.
- Also, since the description supports HTML markup as well, a proper use case about the package usage/how to use the package would be helpful.
- There's a `Clicks` statistic for the ads, I tried adding a `link` tag and tried clicking but the click count didn't increase, so maybe I can't figure out how to use it, so a use case of this feature would also be helpful

**Comment by tushargugnani** [comment]
@tapan288 
1. I tried installing the package on a fresh project and the smart-ad-dashboard looks to be working fine without running npm cmomands, please try this again.
2. I have added the documentation on how to go about Auto ad placements, Please try again.
3. I have added a image which shows how to create a new Ad. (should be helpful to see what kind of data goes into the body)
4. added the documentation on how to go about tracking clicks, please test again.

**Comment by tapan288** [comment]
@tushargugnani
So I have this sample ad added:
![image](https://user-images.githubusercontent.com/46927593/211451081-bc84902b-bb56-432e-8c79-e44817abe807.png)

But I'm getting an error
`Uncaught (in promise) DOMException: Document.querySelector: '' is not a valid selector`  on line 7 of `smart-ads.js`
Also tried adding an ID attribute to the ad, still same error. So, because of this, the click is not working

**Comment by tushargugnani** [comment]
@tapan288 I have pushed some fixes, please pull and also added a documentation about including meta csrf token for the tracking clicks to work. Please test again.

**Comment by tapan288** [comment]
@tushargugnani
It works now but seems like the ad-blocker hides the element once it gets rendered

**Comment by 5balloons** [comment]
mentioned issues are fixed.
