### ISSUE TITLE
count of click is not working

### ISSUE THREAD

**Issue by EngMustafaSabah** [5balloons/laravel-smart-ads#10]
"php": "^8.1",
        "5balloons/laravel-smart-ads": "^1.1",
        "filament/filament": "^3.0-stable",
        "filament/tables": "^3.0-stable",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8"

**Comment by tushargugnani** [comment]
@EngMustafaSabah which version are you using?

**Comment by EngMustafaSabah** [comment]
@tushargugnani

My composer.json

 "php": "^8.1",
    "5balloons/laravel-smart-ads": "^1.1",
    "filament/filament": "^3.0-stable",
    "filament/tables": "^3.0-stable",
    "guzzlehttp/guzzle": "^7.2",
    "laravel/framework": "^10.0",
    "laravel/sanctum": "^3.2",
    "laravel/tinker": "^2.8"

**Comment by tushargugnani** [comment]
@EngMustafaSabah Can you try upgrading it to v 1.2.8 to see if that fixes it.

**Comment by EngMustafaSabah** [comment]
@tushargugnani 
Thanks its work
