### ISSUE TITLE
fix disabling for manual ad and add it to php8.0 package version

### ISSUE THREAD

**Issue by strorch** [5balloons/laravel-smart-ads#13]
hello, can you please fix disabling for manual added ads by merging this pr #12 
and create a tag for php8.0 with this fix (i`m currently using v1.2.8 and have no possibility to switch php version on server)

**Comment by tushargugnani** [comment]
Merged.

**Comment by strorch** [comment]
can you please apply this fix to version compatible with php8.0 and create new tag 1.2.8-1 or something like that
