### ISSUE TITLE
Validation error on update

### ISSUE THREAD

**Issue by GeneratorEVil** [5balloons/laravel-smart-ads#2]
Hi! 
In StoreSmartAdRequest
rule 
$image_rule = "nullable|image|mimes:jpg,png,jpeg,gif,svg|max:2048";

not working.

**Comment by tushargugnani** [comment]
@GeneratorEVil Are you getting an error while trying to update the ad?

**Comment by tushargugnani** [comment]
@GeneratorEVil Fix has been released in https://github.com/5balloons/laravel-smart-ads/releases/tag/v1.2.3
