### ISSUE TITLE
Error on edit

### ISSUE THREAD

**Issue by GeneratorEVil** [5balloons/laravel-smart-ads#4]
Undefined property: stdClass::$style (View: /vendor/5balloons/laravel-smart-ads/resources/views/smart-ad-manager/edit.blade.php)

1. Add image banner
2. Change auto insertion
3. Try edit - error

In DB JSON
[{"position": "afterbegin", "selector": "#banner-1-mid-en"}]
Have not style param.

**Comment by tushargugnani** [comment]
@GeneratorEVil Will check this, thank you for posting.

**Comment by GeneratorEVil** [comment]
> @GeneratorEVil Will check this, thank you for posting.

And when change banner's title  , slug not updating

**Comment by tushargugnani** [comment]
@GeneratorEVil since slug is used to keep track of ad clicks, it's deliberately kept the same even if the title changes.

**Comment by tushargugnani** [comment]
Fixed in v1.2.6
