### ISSUE TITLE
how to restrict admin page to me (the admin)

### ISSUE THREAD

**Issue by EeKay** [5balloons/laravel-smart-ads#7]
hey @5balloons, firstofall: awesome package. Love the clean and sweet features.

I'm wondering how i can properly make it accessible for me as an admin only, without editing the vendor files.
Are there any config things i can set?

**Comment by tushargugnani** [comment]
@EeKay You can create a middleware for the admin users roles and add that to the middleware property in the smart-ads config file
```'middleware' => ['web', 'admin'],```

**Comment by EeKay** [comment]
Thanks 🙏🏻, missed that config setting somehow. Already cooked up admin middleware using [this medium post](https://medium.com/@arvind.mailto/how-to-create-custom-routes-for-protected-admin-manager-area-in-laravel-8-75e5b5a20b88).

Working like a charm now. Thanks for this nifty ads package
